# from pathlib import Path
# s=Path('.').resolve().joinpath('models','autogeneratedmodel.py').open('rt',encoding='utf8').read()
# import re
# classname='Orderitem'
# re.findall(rf'(class {classname}\(B.*?)class',s,re.S+re.M)
# def x(matched):
#     print(f'len:',len(matched.groups()))
#     print(matched.groups())
#     return matched.groups()[0]+(matched.groups()[2] if len(matched.groups())>=3 else '')

import threading
import requests
import random
def main():
    while 1:
        print(12)
        url='http://127.0.0.1:8000/api/user/register'
        data={
        "username": random.randint(100000,99999999),
        "password": "123456",
        "repassword": "123456",
        "phone": "18606206145",
        "email": "y.blz@qq.com"
        }
        ret=requests.post(url,json=data)
        print(ret.json())
ths=[threading.Thread(target=main) for i in range(1)]
[th.start() for th in ths]
[th.join() for th in ths]