from component.snowFlakeId import snowFlack
from sqlalchemy import Column, DateTime, Float, ForeignKey, text,Text
from sqlalchemy.dialects.mysql import BIGINT, DATETIME, ENUM, INTEGER, VARCHAR
from sqlalchemy.orm import relationship

from .autogeneratedmodel import Base

class Log2(Base):
    __tablename__ = 'log'

    id = Column(BIGINT, primary_key=True,default=snowFlack.getId)
    msg=Column(Text, nullable=True)
    create_at = Column(DateTime)
    update_at = Column(DateTime)
    delete_at = Column(DateTime)
    is_deleted = Column(INTEGER(11), server_default=text("'0'"))


